### ISSUE TITLE
Verify Python 3 compatibility for OctoPrint 1.4

### ISSUE THREAD

**Issue by battis** [battis/OctoPrint-LDAP#3]
This may actually be a bit more involved, since it looks like the `UserFactory` object has been redesigned (in good ways) in OctoPrint 1.4, which may entail more updates that make the plugin not reverse-compatible to OctoPrint 1.3.

**Comment by paukstelis** [comment]
Any plans to tackle this now that OP 1.4 is out?

**Comment by battis** [comment]
Yes. Actually. I'm working with @gillg to get this fork merged all the way into his original plugin. I took  a quick glance at version 1.4 a while back, and my big impression was not that Python 3 would be the big issue, but that the structure of the UserManager class was shifting and that we might have to redesign how we plugin the authentication scheme.

I'm moving slowly right now though (I teach high school which is its own thing... but now we're also dealing with COVID-19 preparedness, which demands even more attention). So the ETA is a little nebulous. I'm hoping to either have some bandwidth to think about all this in late April, during Passover, or when we hit May.

**Comment by paukstelis** [comment]
Cool. I forked your fork and started working on it (testing branch). I got it to a somewhat functional state with 1.4 (caching and cached users seem to work fine). Some issues with retrieving groups properly, but that's probably due to the new GroupManager.

**Comment by towo** [comment]
For some debugging:
```
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/__init__.py", line 423, in run
    userManager = factory(components, self._settings)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_auth_ldap/__init__.py", line 306, in ldap_user_factory
    return LDAPUserManager(plugin=self)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_auth_ldap/__init__.py", line 39, in __init__
    FilebasedUserManager.__init__(self, **kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
```

**Comment by battis** [comment]
Hmm. @towo That looks familiar from my first pass at it. My recollection (which is a little dusty at the moment, but will get brushed up shortly) is that the internal structure of user management shifted in 1.4, and that this plugin hooks until in creative, but now-changed, ways that need to be tweaked.

School has ended, and I'm in the midst of re-purposing my home office from remote teaching broadcast studio to off-site lab development workshop. This is high on my list. Hoping to have some resolution by mid-July.

**Comment by paukstelis** [comment]
Have a look at my fork. I have a functional version: https://github.com/paukstelis/OctoPrint-LDAP/tree/testing

**Comment by battis** [comment]
@paukstelis Ooo! Hot! I'll check it out.

**Comment by battis** [comment]
Pulled in @paukstelis's fork, did some further clean-up work. It works (at least, in my testing so far -- I haven't tried it on campus against our Microsoft LDAP server... but I think that all the issues are local to OctoPrint itself, so I'm not super-worried).

In 1.0, the LDAP groups (that were part of the LDAP group filter) of which an LDAP user was a member were cached in the `group` field of the `users.yaml`. This had a lot of merit, I thought, since it meant that user access could be controlled at the LDAP side as well as the OctoPrint side (use case: "all members of the `Current Students` LDAP group are able to log in to OctoPrint... but when they are removed from `CurrentStudents` they can't log in." Plus, in the new, more granular permissions world, it seems possible to go one better, by mapping an LDAP group like `Faculty` on to an mirrored OctoPrint group and giving that group admin privileges in OctoPrint. For example.)

Most of the work I just did (https://github.com/battis/OctoPrint-LDAP/commit/84755002bec8a7a8a55f977d1a2bb69d09b31f94) was focused on making a tidy transition from old-style `users.yaml` and `config.yaml` to new-style. Hopefully I can bang out the groups thing in the next day or two.

**Comment by battis** [comment]
Ok, as of [this afternoon](https://github.com/battis/OctoPrint-LDAP/commit/1b99325a209d408f2e4f08b26b2da741da59ecbb), I think this is ready to go. I want to tidy up the settings dialog some and make a run to school to test it against Microsoft LDAP, and then we'll get this thing pulled over to [gillg/OctoPrint-LDAP](https://github.com/gillg/OctoPring-LDAP) set up on the plugin repo. Woo hoo!

**Comment by battis** [comment]
Finally got off dad-duty and Zoom calls long enough to run into school. Things appear copacetic when configured against Microsoft LDAP as well. There are some lingering settings issues (values cleared in the GUI get set to `''` rather than the default `None`) that I'll look at this afternoon. I've also been looking at either making errors around missing python-ldap build dependencies nicer (very likely) or automating the install of those dependencies (very unlikely).

I'll get those sorted, push this to v1.1 in @gillg's repo and then register with the plugin repo.
