### ISSUE TITLE
Does not load -  __init__() takes at least 2 arguments

### ISSUE THREAD

**Issue by paukstelis** [battis/OctoPrint-LDAP#4]
Thought I would give this a shot to simplify access control. Seems to install OK, but plugin does not load:

> Traceback (most recent call last):
>   File "/home/paul/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1079, in load_plugin
>     plugin.load()
>   File "/home/paul/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_auth_ldap/__init__.py", line 203, in __plugin_load__
>     __plugin_implementation__ = LDAPUserManager()
> TypeError: __init__() takes at least 2 arguments (1 given)

I'm using OP 1.4.0 rc4.

**Comment by paukstelis** [comment]
Issue solved. README installation link still points to the root branch, not this fork. Installing from the fork works.

**Comment by paukstelis** [comment]
Still with issues on this. Looks like OP introduced FilebasedGroupManager in 1.4, so the FilebasedUserManager does not instantiate.

**Comment by battis** [comment]
Resolved. By your work!

https://github.com/paukstelis/OctoPrint-LDAP/commit/74cef9c75b9a5349513cc172f0d2f5861e0bfc03
